services:
  - type: web
    name: taskflow-backend
    env: python
    region: frankfurt
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DATABASE_URL
        value: postgresql://taskflow_db_a8cq_user:lpivY4sDPZyVPPcgQlToRRMqsh1noGjt@dpg-d96ahla8qa3s738lt1g0-a/taskflow_db_a8cq
      - key: SECRET_KEY
        value: taskflow-super-secret-key-2026-kishore-germany
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: REFRESH_TOKEN_EXPIRE_DAYS
        value: 7
      - key: GROQ_API_KEY
        value: your-groq-api-key
      - key: AWS_ACCESS_KEY_ID
        value: your-aws-key
      - key: AWS_SECRET_ACCESS_KEY
        value: your-aws-secret
      - key: AWS_BUCKET_NAME
        value: kishore-dev-bucket-storage
      - key: AWS_REGION
        value: us-east-1